#################################################
#                                               #
#            CONFIGURAÇÃO DO SISTEMA            #
#                                               #
#################################################

#Configuração do MySQL
MySQL:
  Usar: false
  IP: 'localhost'
  Porta: '3306'
  Database: ''
  Usuario: ''
  Senha: ''
  
#Se deseja verificar as atualizações do plugin, ative isso
Verificar-Atualizacoes: true

#Se deseja enviar uma mensagem aos administradores sobre novas atualizações, ative isso
Avisar-Administradores: true

#Caso queira usar UUIDs como forma de armazenamento no MySQL, ative
#Flatfile SEMPRE usará UUIDs como forma de armazenamento
Usar-UUIDs: true

#################################################
#                                               #
#            CUSTOMIZAÇÃO DO SISTEMA            #
#                                               #
#################################################

#Aviso:
#Todas as mensagens são configuradas no arquivo mensagens.yml

#Se deseja que o plugin envie uma mensagem privada ao jogador quando upar, ative isso
Enviar-Mensagem: true

#Se deseja que o plugin envie um broadcast quando o jogador upar, ative isso
Anuncio: true

#Se deseja que o plugin envie um broadcast diferenciado quando o jogador upar ao rank maximo, ative isso
Anuncio-Rank-Maximo: true

#Se deseja que o plugin solte um foguete quando o jogador upar, ative isso
Soltar-Foguete: true

#Se deseja enviar titles quando o jogador upar, ative isso e modifique as opções
Title:
  Usar: true
  
  #O modo é a forma como os titles serão enviados.
  #Existem dois modos: Apenas para o jogador que upou (Modo 1) e Todos os jogadores do servidor (Modo 2)
  Modo: 1
  
  #Titulo e Subtitulo são as mensagens que serão exibidas no titles
  #Titulo é o texto de cima; O maior. Subtitulo é o texto de baixo, o menor;
  #Placeholders: 
  #@player = Nome do jogador que upou, @rank = Rank que o jogador upou, @oldrank = Rank que o jogador estava antes de upar
  #@preco = O dinheiro gasto para subir para o rank, @dinheiro = O dinheiro que sobrou após o jogador upar
  Titulo: '&eVocê subiu de rank!'
  Subtitulo: 'Você está agora no rank @rank&r!'

#Se deseja ativar o comando /ranks, que cria um GUI com todas as informações dos ranks, ative isso e configure
GUI:
  Ativar: true
  
  #Coloque aqui o nome do GUI
  #AVISO: Maximo 32 caracteres
  #Placeholders:
  #@player = Nome do jogador que está vendo a GUI, @playerrank = Nome Rank que o jogador está
  #@dinheiro = Dinheiro do jogador
  Nome: '&aMenu de Ranks'
  
  #Abaixo, são as configurações do nome dos Itens e Lore.
  #Todos os itens da GUI serão afetados por essa configuração
  #Placeholders:
  #@player =  Nome do jogador que está vendo a GUI, @rank = Nome do Rank, @preco = Preço do rank
  #@playerrank = Nome do Rank que o jogador está, @dinheiro = Dinheiro que o player tem atualmente
  ItemNome: '&aRank: @rank'
  ItemLore:
  - '&aPreço: &c@preco'
 
#Configuração dos ranks
#Guia de configuração: http://bit.ly/uRankingConfigs
Ranks:
  Noob:
    Nome: '&f&lNoob&r'
    Tag: '&7[&f&lNoob&7]'
    ItemID: '1'
    Preco: 0
    Comandos:
    - 'pex user @player group add noob'
  Mediano:
    Nome: '&a&lMediano&r'
    Tag: '&7[&a&lMediano&7]'
    ItemID: '41'
    Preco: 500
    Comandos:
    - 'pex user @player group remove noob'
    - 'pex user @player group add mediano'
    - 'give @player diamond 5'
  Mito:
    Nome: '&b&lMito&r'
    Tag: '&7[&b&lMito&7]'
    ItemID: '57'
    Preco: 2500
    Comandos:
    - 'pex user @player group remove mediano'
    - 'pex user @player group add mito'
    - 'give @player diamond 10'