name: uRanking
version: 1.2.3
main: ga.brunnofdc.uRanking.Main
author: BrunnoFdc
website: https://www.brunnofdc.ga/
depend: [Vault]
softdepend: [UltimateChat, Legendchat]
commands:
  rankup:
    description: Upa o seu rank
  uranking:
    description: Administra o sistema de ranks
permissions:
  uranking.rankup:
    default: false    
  uranking.hidetag:
    default: false
